version: 2

sources:
  - name: staging
    database: data-engineer-project-384504
    schema: de_project_dataset

    tables:
      - name: us_accidents

models:
  - name: us_accidents_table
    description: "Model with raw us accidents data"
    columns:
      - name: ID
        description: "This is a unique identifier of the accident record"
        tests:
          - unique
          - not_null
      - name: severity
        description: "Shows the severity of the accident, a number between 1 (less) and 4(most)"
        tests:
          - accepted_values:
              values: ['1', '2', '3', '4']
      - name: start_time
        description: "Shows start time of the accident in local time zone"
        tests:
          - not_null
      - name: end_time
        description: "Shows end time of the accident in local time zone"
        tests:
          - not_null
      - name: description
        description: "Shows a human provided description of the accident"
        tests:
          - not_null
      - name: state 
        description: "Shows the state in address field"
        tests: 
          - not_null
      - name: weather_condition 
        description: "Shows the weather condition (rain, snow, thunderstorm, fog, etc.)"
        tests: 
          - not_null

  - name: us_accidents_clustered_weather
    description: "Model with partitioned and clustered us accidents data"
    columns:
      - name: weather_condition 
        description: "Shows the weather condition (rain, snow, thunderstorm, fog, etc.)"
        tests: 
          - not_null
      - name: num_accidents 
        description: "Count the number of accidents"
      - name: average_Severity 
        description: "Average of accidents severity"

  - name: us_accidents_clustered_state
    description: "Model with partitioned and clustered us accidents data"
    columns:
      - name: state 
        description: "Shows the state in address field"
        tests: 
          - not_null
      - name: num_accidents 
        description: "Count the number of accidents"
      - name: average_Severity 
        description: "Average of accidents severity"  

  - name: us_accidents_partitioned_clustered_fullDate
    description: "Model with raw us accidents data"
    columns:
      - name: state 
        description: "Shows the state in address field"
        tests: 
          - not_null
      - name: StartTime
        description: "Shows start time of the accident in local time zone"
        tests:
          - not_null
      - name: severity
        description: "Shows the severity of the accident, a number between 1 (less) and 4(most)"
        tests:
          - accepted_values:
              values: ['1', '2', '3', '4']
      - name: ID
        description: "This is a unique identifier of the accident record"
        tests:
          - not_null
      - name: weather_condition 
        description: "Shows the weather condition (rain, snow, thunderstorm, fog, etc.)"
        tests: 
          - not_null
