version: 2

sources:
  - name: staging
    database: data-engineer-project-384504
    schema: de_project_dataset

    tables:
      - name: us_accidents
      - name: us_accidents_partitioned_clustered

models:
    - name: us_accidents2
      description: Basic data with us accidents
